---
application:
  name: "oauth2-authenticate"
  project: "ZynKyApp"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "z-ecommerce-db"
  version: "4.4"
- type: "MYSQL"
  name: "z-ecommerce-db"
  version: "8"
routers:
- name: "main-oauth2-authenticate"
  routes:
  - application_name: "oauth2-authenticate"
    paths:
    - "/*"
